INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (1, '1','Pintura de uñas','Valmy', 2, 7, 23, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (2, '2','Limas','Chinas', 10, 15, 10, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (3, '3','Cortauñas','', 6, 11, 9, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (4, '4','Guillotina','', 2, 7, 3, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (5, '5','HydraCare','facial', 9, 14, 12, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (6, '6','Exfoliante','Pond´s', 2, 7, 7, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (7, '7','Exfoliante','Sabonina', 1, 6, 4, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (8, '8','Hidratacion profunda','Sabonina', 6, 11, 4, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (9, '9','Crema','Dove 75ml', 4, 9, 1, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (10, '10','Crema','Nivea 150ml', 3, 8, 7, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (11, '11','Repujador','', 2, 7, 10, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (12, '12','Limas dobles','', 6, 11, 12, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (13, '13','Polvos con espejo','Valmy', 1, 6, 14, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (14, '14','Polvos doble funcion','Valmy', 8, 13, 12, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (15, '15','Polvos sin espejo','Valmy', 6, 11, 3, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (16, '16','Labiales','Flormar', 10, 15, 17, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (17, '17','Correctores','Flormar', 2, 7, 24, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (18, '18','Polvos doble funcion','Flormar', 4, 9, 22, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (19, '19','Polvos sencillos','Flormar', 4, 9, 13, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (20, '20','Brillos de labio','Niña', 10, 15, 23, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (21, '21','Lapiz para cejas','MAC', 9, 14, 15, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (22, '22','Lapiz negro','Sephers', 1, 6, 6, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (23, '23','Polvo compacto','Stives', 8, 13, 17, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (24, '24','Kit de brochas','Ecootols', 3, 8, 10, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (25, '25','Labiales','Jakelin', 4, 9, 19, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (26, '26','Labiales','Maybelline', 4, 9, 23, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (27, '27','Labiales cremosos','La girls', 10, 15, 18, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (28, '28','Labiales mate','La girls', 3, 8, 18, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (29, '29','Labiales','Sephers', 5, 10, 14, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (30, '30','Labiales','Valmy', 6, 11, 17, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (31, '31','Labiales','Orly', 4, 9, 2, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (32, '32','Lapiz','Sephers', 4, 9, 12, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (33, '33','Delineador','Maybelline', 10, 15, 17, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (34, '34','Correctores','Maybelline', 6, 11, 16, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (35, '35','Polvo','Fit me', 1, 6, 5, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (36, '36','Correctores en crema','La girls', 3, 8, 23, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (37, '37','Rubores','Sephers', 9, 14, 3, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (38, '38','Rubores','Valmy', 3, 8, 13, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (39, '39','Sobras','Maybelline', 8, 13, 7, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (40, '40','Mini paletas','Maybelline', 8, 13, 18, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (41, '41','Sombras','Orly', 3, 8, 12, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (42, '42','Iluminadores','Maybelline', 2, 7, 16, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (43, '43','Iluminadores','La girls', 7, 12, 24, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (44, '44','bronceadores','Maybelline', 5, 10, 2, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (45, '45','lapiz','Maybelline', 9, 14, 21, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (46, '46','sobras','valmy', 6, 11, 9, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (47, '47','Correctores','La girls', 4, 9, 10, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (48, '48','Sombras','Flormar', 2, 7, 2, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (49, '49','Labiales','Chinas', 8, 13, 4, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (50, '50','rimel','Sephers', 1, 6, 5, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (51, '51','labiales mate','Sephers', 6, 11, 2, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (52, '52','delineador en crema','La girls', 3, 8, 6, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (53, '53','plantilla para delinearse el ojo','', 4, 9, 6, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (54, '54','emponjas','Valmy', 8, 13, 19, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (55, '55','emponjas','Chinas', 3, 8, 14, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (56, '56','cepillos para plancha','', 10, 15, 24, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (57, '57','brochas','chinas', 4, 9, 23, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (58, '58','brochas','Maybelline', 3, 8, 1, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (59, '59','Bbcream','La girls', 2, 7, 14, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (60, '60','Base','La girls', 10, 15, 20, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (61, '61','base','Maybelline', 2, 7, 13, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (62, '62','base','Flormar', 10, 15, 6, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (63, '63','Bbcream','Flormar', 5, 10, 11, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (64, '64','Base velvet','Maybelline', 8, 13, 19, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (65, '65','correctores','valmy', 3, 8, 10, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (66, '66','bases','valmy', 1, 6, 23, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (67, '67','lapiz de labio','Sephers', 4, 9, 24, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (68, '68','lapiz de labio','Maybelline', 7, 12, 3, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (69, '69','lapiz de ojo','Maybelline', 8, 13, 22, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (70, '70','lapiz de labio','La girls', 9, 14, 19, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (71, '71','acetona','valmy', 3, 8, 3, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (72, '72','desodorante','rexona', 8, 13, 10, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (73, '73','desodorante','axcel', 8, 13, 22, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (74, '74','desodorante para caballero','dove', 3, 8, 21, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (75, '75','desodorante para dama','dove', 1, 6, 3, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (76, '76','desodorante','active fresh', 8, 13, 3, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (77, '77','mascarilla anticaida','', 6, 11, 24, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (78, '78','crema de peinar','every night', 8, 13, 18, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (79, '79','palitos para puntos negros','', 4, 9, 1, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (80, '80','toallitas desmaquillantes','', 6, 11, 17, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (81, '81','removedor de esmalte','', 2, 7, 13, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (82, '82','crema corporal','slik', 8, 13, 17, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (83, '83','crema','alizzets', 5, 10, 23, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (84, '84','afeitadoras','', 2, 7, 14, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (85, '85','ampolla','slik', 4, 9, 14, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (86, '86','Shampoo','defile', 9, 14, 19, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (87, '87','Shampoo','pantene', 1, 6, 20, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (88, '88','shampoo pequeño','drene', 7, 12, 10, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (89, '89','shampoo grande','drene', 5, 10, 3, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (90, '90','shampoo adulto','every night', 10, 15, 21, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (91, '91','shampoo niño','every night', 7, 12, 23, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (92, '92','shampoo','menen', 5, 10, 16, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (93, '93','shampoo grande','jhonsom', 3, 8, 18, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (94, '94','shampoo pequeño','jhonsom', 1, 6, 19, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (95, '95','shampoo pequeño','dove', 4, 9, 9, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (96, '96','Gel de baño','', 5, 10, 22, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (97, '97','shampoo','vo5', 9, 14, 4, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (98, '98','desinfectantes','', 1, 6, 12, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (99, '99','acondicionador','drene', 5, 10, 7, '');
INSERT or IGNORE INTO productos(id, codigo, nombre, marca, precioCompra, precioVenta, stock, descripcion)VALUES (100, '100','acondicionador','every night', 5, 10, 1, '');